project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "Benise Limon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - maps.qmd
      - ELI.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

